config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'resume' => 'welcome#resume'
  get 'papers' => 'welcome#papers'
  get 'noze' => 'welcome#noze'
  get 'imagination' => 'welcome#imagination'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def resume
  end

  def papers
  end

  def noze
  end

  def imagination
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body style='width:1000px; margin: auto'>
    <nav class="navbar" role="navigation">
      <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index">Portfolio</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", about_path%></li>
            <li><%= link_to "Resume", resume_path%></li>
            <li><%= link_to "Publications", papers_path%></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

<!--  Don't know what this was for.....
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54891143-1', 'auto');
    ga('send', 'pageview');

  </script>
 -->

app/views/welcome/about.html.erb
<div class="container-fluid bkgrd">
  <div class='page-container'>
	  <div class='text-container'>
			<h3 style="color:#0000b3;text-align:center">RAILS & RUBY EXPERIENCE</h3><br>

			<div class="row">
				<div class="col-md-6">
					<div>
						<%= image_tag('SamSkinner.jpg', height:'240', width:'320', :class=>"img-rounded img-border", title:"Yours Truly")%>
					</div>  <!-- close div image -->
					<div>
						<p><i>Rubyist and Ruby-on-Rails developer. Entrepreneur. Biologist.</i>  I've worn several hats over the years.  Currently, I'm very excited to transition to a new career as a Ruby and Ruby-on-Rails developer.</p>
						<p>Briefly, I took the Code Immersion program offered by Tech Talent South (TTS) in July through mid-September of 2014.  TTS then hired me to <b><i>teach that same course</i></b> during their October to December session.  I split the teaching with another; she taught the front-end material while I taught the Ruby and core Rails sections (i.e., scaffolding, databases, model associations). Links to some of my slide decks from that course are below.</p>
						<p>Recently I built a new website for TTS, a <a href= "http://jobs.techtalentsouth.com"><u>jobs board</u>.</a> A second completed project, this time collaborative, is an app for picking game winners and bantering among friends for sports fans.  See <a href= "http://picknoze.com"><u>picknoze</u>.</a></p>
					</div> <!-- close div Rubyist -->
				</div>  <!-- close div col-md-6 -->
				<div class="col-md-6">	
					<h5>COMPETENCIES:</h5>
					<ul>
							<li>Basic <b>GIT/Github</b> – pull requests, branch, merge, clone, commit, push</li>
							<li>Basic <b>RVM</b> –create & manage gemsets with Ruby Version Manager</li>
							<li><b>Ruby</b>: Familiar with many aspects, including benchmarking & profiling & use of libraries and gems.</li>
							<li><b>Rails:</b> Setup and deploy an App for production using Github and Heroku</li>
							<li><b>Rails:</b> Set up and use API’s such as Google Maps and Amazon Web Services</li>
							<li><b>Rails:</b> Create all seven types of  model associations (including many-to-many & polymorphic) and all basic data validations and filters</li>
							<li><b>Rails:</b> Understand and use Active Record associations</li>
							<li><b>Rails:</b> Understand and use Object Oriented Programming</li>
							<li><b>Rails:</b> Use generators to create models, controllers and migrations</li>
							<li><b>Rails:</b> Create and use migrations to manage databases</li>
							<li><b>Rails:</b> Handle CRUD requests using a Controller, Model, and View</li>
							<li><b>Rails:</b> Setup a Rails environment on Macs, Windows and Ubuntu</li>
							<li>Working knowledge of <b>HTML5, CSS3</b> and some Javascript.</li>
					</ul>				
				</div>  <!-- close div col-md-6 -->
			</div>  <!-- close div row -->

			<div class="panel panel-default", id='slide-container'>
				<div>
					<h5>REPRESENTATIVE SLIDE DECKS I PREPARED FOR THE TTS CODE IMMERSION COURSE:</h5>
				</div>
				<div>
					<a href="http://slides.com/pipefish1/from-the-ground-up"><u style="color:mediumblue">From the Ground Up</u></a>
					<p>Create an app -–without scaffolding-- that uses polymorphic associations among models and nested resources.</p>

					<a href="http://slides.com/pipefish1/models-databases-iii"><u style="color:mediumblue">Model Associations</u></a>
					<p>One-to-many and many-to-many associations, set up the model relationships and refactor code in controllers and views to display the associated data.</p>

					<a href="http://slides.com/pipefish1/scaffolding-models-databases-i"><u style="color:mediumblue">Scaffolding, Models, Databases</u></a>
					<p>The first of four sessions on the heart of Rails.</p>

					<a href="http://slides.com/pipefish1/the-developer-s-tools-git-github-heroku"><u style="color:mediumblue">A Developer's Toolkit</u></a>
					<p>A developer’s toolkit: git, github and heroku.</p>

					<a href="http://slides.com/pipefish1/from-zero-to-deploy-rails-github-heroku-11-12"><u style="color:mediumblue">From Zero to Deploy</u></a>
					<p>A whirlwind tour through creating an app and deploying it to the web.</p>
				</div>
			</div>  <!-- close div panel -->
			<div>References available on request.</div>
		</div>  <!-- close div text-container -->
	</div>  <!-- close div page-container -->
</div>  <!-- close div container-fluid bkgrd -->

app/views/welcome/imagination.html.erb
<div class='container-fluid'>
<br>
<br>
<p style="color:#F4F4ED; font-family:fantasy; font-size:100px; text-align:center"><i>-It's Just My</i></p><br><br>
<span style="color:#F4F4ED; font-family:fantasy; font-size:100px; text-align:center"><i>Imagination-</i></span>

<audio src="/assets/imagination.mp3" autoplay loop></audio>

</div>

app/views/welcome/index.html.erb
<div class="container-fuid">
  <div><h2 style="text-align:center"; abbr title="fan of hiking, kayaking & coding">Sam Skinner, PhD | Portfolio</abbr></h2>
  </div>
  <div style='width: 95px; margin: auto'>
    <a href="https://github.com/freedomevolves"><%= image_tag("github.png", height:"30", width:"35", title:"GitHub")%></a>&nbsp;&nbsp;
    <a href="http://www.linkedin.com/in/samskinnerphd"><%= image_tag("linkedin.jpeg", height:"30", width:"32", title:"LinkedIn") %></a>
  </div>
  <br><br> <br> <br> <br><br>
  <div style='width: 700px; margin: auto'>
    <a href= "http://jobs.techtalentsouth.com"><%= image_tag("tts-logo.png", height:'200', width:'200', :class=>"img-rounded img-border", title:"A jobs board I built for TTS.") %></a>
    <a href= "http://picknoze.com"><%= image_tag('noze.jpg', height:'200', width:'200', :class=>"img-rounded img-border", title:"A collaborative freelance project with Garey Simpson, commissioned by Noze, LLC.") %></a>
    <%= link_to(image_tag('nasonia.jpg', height:'200', width:'200', :class=>"img-rounded img-border", title:"Female Nasonia decide the sex of their offspring as they lay their eggs.  My research focused on understanding the evolutionary, ecological, behavioral and genetic underpinnings of this behavior."), resume_path) %>    
  </div>
</div>
<br>

app/views/welcome/noze.html.erb
<h3>A collaborative freelance project with Garey Simpson.</h3>
<h3>Commissioned by Noze, LLC.</h3>
<h3>Launch: mid-April.</h3>

app/views/welcome/papers.html.erb
 <div class="container-fluid bkgrd">
   <div class='page-container'>
	   <div class='text-container'>

				<h2 style="text-align:center">Scientific Publications</h2>
				<br>
				<a href="http://scholar.google.com/citations?hl=en&user=tFD9hkgAAAAJ"><u style="color:mediumblue">Google Scholar</u></a>
				<br><br>
				<div>
					<p>King, B. H., Crowe, M. L. and S. W. Skinner.  1995.  Effect of host density on offspring sex ratios and behavioral interactions between females in the parasitoid wasp, <i>Nasonia vitripennis</i>.  J. Insect Behavior 8: 89-102.</p>

					<p>Skinner, S. W. 1993.  Experimental evolution of a 1:1 sex ratio under random mating.  Submitted to  Nature, available on request.</p>

					<p>King, B. and S. W. Skinner.  1991.  Sex ratio in a new species of <i>Nasonia</i> with fully- winged males.  Evolution 45: 225-228.</p>

					<p>King, B. and S. W. Skinner.  1991.  Proximal mechanisms of the sex ratio and clutch size responses of the wasp <i>Nasonia vitripennis</i> to parasitized hosts.  Animal Behav. 42: 23-33.</p>

					<p>O'Neill, K. M. and S. W. Skinner.  1990.  Body size and ovarian egg number in parasitoid wasps: Implications for variation in female reproductive success.  J. Zool. 220: 115-122.</p>   

					<p>Charnov, E. L. and S. W. Skinner.  1988. Clutch size in parasitoids: the egg production rate as a constraint.  Evol. Ecol. 2: 167-174.</p>

					<p>Skinner, S. W. 1987.  Paternal transmission of an extrachromosomal factor in a parasitoid wasp: evolutionary implications.  Heredity 59: 47-53.</p>

					<p>Werren, J. H., Skinner, S. W. and A. M. Huger.  1986.  Male-killing bacteria in a parasitoid wasp.  Science 231: 990-992.</p>

					<p>Skinner, S. W.  1985.  son-killer: A third extrachromosomal factor affecting the sex ratio in the parasitoid wasp, <i>Nasonia (=Mormoniella) vitripennis</i>.  Genetics 109: 745-759.</p> 

					<p>Skinner, S. W.  1985.  Clutch size as an optimal foraging problem for insects.  Behav. Ecol. Sociobiol. 17: 231-238.</p>

					<p>Charnov, E. L. and S. W. Skinner.  1985.  Complementary approaches to understanding parasitoid oviposition decisions.  Environ. Entomol. 14: 383-391.</p>

					<p>Huger, A. M., Skinner, S. W. and J. H. Werren.  1985. Bacterial infections associated with the son-killer trait in the parasitoid wasp, <i>Nasonia vitripennis</i>. J. Invert. Path. 46: 272-282.</p>

					<p>Charnov, E. L. and S. W. Skinner.  1984.  Evolution of host selection and clutch size in parasitoid wasps.  Fla. Entomol. 67: 5-21.</p>

					<p>Skinner, S. W.  1982.  Maternally inherited sex ratio in the parasitoid wasp, <i>Nasonia vitripennis</i>.  Science 215: 1133-1134.</p>

					<p>Werren, J. H., Skinner, S. W. and E. L. Charnov.  1981.  Paternal inheritance of a daughterless sex ratio factor.   Nature 293: 467-468.</p> 

					<p>Skinner, S. W. and J. S. Lockard.  1979.  An ethogram of the lion-tail macaque (<i>Macaca silenus</i>) in captivity.  Appl. Animal Ethol. 4: 241-53.</p>
					
				</div>
		</div>
	</div>
</div>

app/views/welcome/resume.html.erb
<div class="container-fluid bkgrd">
  <div class='page-container'>
    <div class= 'text-container'>     
        <h2 style="text-align:center">Sam Skinner, PhD</h2>
        <div style="text-align:center">Roswell, GA | 678-585-7757 | samskinnerphd@gmail.com </div>
        <div style="text-align:center">
        <a href="https://github.com/freedomevolves"><u style="color:mediumblue">Github</u></a>  || 
        <a href="https://www.linkedin.com/pub/sam-skinner-phd/60/822/723"><u style="color:mediumblue">LinkedIn</u></a>
        </div>       
        <br>       
        <h4><u>EDUCATION</u></h4>
        <div>Rails Web Development, Tech Talent South.  July- September 2014.<br>
        Ph. D., University of Utah.  1983. <br>
        B. A., University of Washington.  1978. </div>
        <br>
        <h4><u><%= link_to "SEE MY RAILS/RUBY EXPERIENCE", about_path%></h4></u><br>

        <h4><u>BUSINESS OWNER</u></h4>
        <div>President, OneSource Brokers, Inc. February 1996 – June 2014.<br>
        OneSource Brokers helped businesses develop and implement multi-year strategies for bringing their health insurance costs under control. Consultant on market changes due to the Affordable Care Act.

        <h5>Professional achievements:</h5>
        <ul>
          <li>Seasoned professional in B2B marketing and lead generation.</li>
          <li>Exceptional year-over-year retention of clients (2X industry average).</li>
          <li>Exemplary reputation, with demonstrated ability to interact with all levels of personnel while maintaining the highest standards of professionalism and customer service.</li>
          <li>Broad competency in Human Resources issues and benefits management.</li>
          <li>Invented and pioneered use of “cost/risk” analysis in advising health insurance purchases, a technique now widely used in the industry.</li>
          <li>Early innovator in combining automatic dialers with fax machines to create wildly successful marketing campaign on which I built this business. (Mid- 90's. Yes, how quaint! How the world has changed!)</li>
        </div>
        <br>

        <h4><u>ACADEMIC POSITIONS</u></h4>
        <div>Visiting Professor, Department of Biology, Emory University, Atlanta, GA.  1993-95.<br>
        Assistant Professor, Dept. of Biology, Indiana University, Bloomington, IN.  1985-93.<br>
        Fellow, Institute for Molecular & Cellular Biology, Indiana University, IN.  1988-93.<br>
        NSF Postdoctoral Fellow, Dept. of Biology, University of Chicago, Chicago, IL.  1985-86.<br>
        NIH Postdoctoral Fellow, Dept. of Genetics, Univ. of Wisconsin, Madison, WI.  1983-85.<br>
        Teaching Fellow, Dept. of Biology, University of Utah, Salt Lake City, UT.  1978-83.</div>
        <br>
        <h4><u>FORMER RESEARCH</u></h4>
        <ul>
           <li>Experimental evolution of sex ratio behavior (evolution of Fisherian sex ratios in experimental populations of a parasitoid wasp, <i>Nasonia vitripennis</i>).</li> 
           <li>Fieldwork on mating behavior and local mate competition in parasitoid wasps.</li>
           <li>Experimental population dynamics of host-parasite interactions (population dynamics of three sex-ratio parasites in a wasp host).</li>
           <li>Molecular biology of male-killing genes in the &#34;son-killer&#34; bacterium,
        	 <i>Arsenophonus nasoniae</i>, a sex-ratio parasite of <i>Nasonia</i> species.</li>	 
        </ul>
        <br>
        <h4><u>MAJOR GRANTS AND FELLOWSHIPS</u></h4>

        <div>NSF Population Biology, 1992-94, <i>Natural Selection for the Sex Ratio.</i>, $161,000.<br>
        NSF Research Training Grant, 1990-95, <i>Center for the Integrative Study of Animal Behavior</i>, $1,500,000,  Supporting PI for Co-Principals: Ellen Ketterson & William Timberlake.<br>
        NSF Biological Bases of Behavior, 1989-91, <i>Sex Ratio Behavior & Ecology of the wasp, Nasonia vitripennis.</i>, $90,000.<br>
        NSF Postdoctoral Fellowship in Environmental Biology, 1985-86, Department of Biology, University of Chicago, Chicago, IL (with M. J. Wade).<br>
        NIH Postdoctoral Fellowship, 1983-85, Department of Genetics, University of Wisconsin, Madison, WI (with J. F. Crow).<br>
        NSF Population Biology, 1982-85, <i>Oviposition Behavior and Sex Ratio in the Parasitoid Wasp, Nasonia vitripennis.</i>, $72,000.</div>
        <br>

        <h4><u>INVITED LECTURES</u></h4>
        <div>Miami University, Dept. of Zoology, Oxford, OH, 1994.<br>
        Savannah River Ecology Laboratory, Aiken, SC, 1994.<br>
        Eastern Illinois University, Dept. of Biology, Charleston, IL, 1994.<br>
        Emory University, Dept. of Biology, Atlanta, GA, 1993, 1994.<br>
        Entomological Society of America, Annual National Meeting, Symposium on “Sex Determination in Insects”, Baltimore, MD, 1992.<br>
        DePauw University, Dept. of Biology, Greencastle, IN, 1991.<br>
        Indiana State University, Dept. of Zoology, Terre Haute, IN, 1991.<br>
        Co-organizer (w/ K. Clay), Symposium on “Host-Parasite Interactions and the Evolution of Reproductive Characteristics", International Congress of Systematics and Evolutionary Biology, College Park, MD, 1990.<br>
        Panelist, Round Table Discussion on “Coevolution: Host/Parasitoid”, International Congress of Systematics & Evolutionary Biology, College Park, MD, 1990.<br>
        Michigan State University, Depts. of Entomology & Zoology, East Lansing, MI, 1990.<br>
        Special Invitee, European Society for Evolutionary Biology, Annual Meeting, Symposium on <i>Norms of Reaction & the Evolution of Life History Traits</i>, Rome, Italy, Sept 1989.<br>
        Ohio State University, Dept. of Entomology, Columbus, OH, 1989.<br>
        University of Illinois, Dept. of Entomology, Urbana, IL, 1988.<br>
        Entomological Society of America, Annual National Meeting, Symposium on <i>Evolution and Diversity of Sex Ratio in Arrhenotokous Insects and Mites</i>, Louisville, KY.  1988.<br>
        Keynote Speaker, Universite de Pau et des Pays de l'Adour, Pau, France, Annual Meeting of the French Entomological Society, 1987.<br>
        North Carolina State University, Dept. of Genetics, Raleigh, NC, 1987.<br>
        Midwest Population Biology Conference, Indiana University, Bloomington, IN, 1986.<br>
        Kellogg Biological Research Station, Michigan State University, Hickory Corners, MI, 1986.<br>
        Northern Illinois University, Dept. of Biology, DeKalb, IL, 1986.<br>
        University of Tennessee, Dept. of Microbiology & Immunology, Memphis, TN, 1986.<br>
        University of California-Irvine, Depts. of Ecology & Evolutionary Biology, Irvine, CA, 1986.<br>
        William and Mary College, Dept. of Biology, Williamsburg, VA, 1985.<br>
        University of Chicago, Dept. of Biology, Chicago, IL, 1985.<br>
        University of California, Santa Barbara, Dept. of Biological Sciences, Santa Barbara, CA, 1985.<br>
        Indiana University, Dept. of Biology, Bloomington, IN, 1985.<br>
        University of Iowa, Dept. of Zoology, Iowa City, IA, 1985.<br>
        Northwestern University, Dept. of Ecology & Evolutionary Biology, Evanston, IL, 1985.<br>
        University of Minnesota, Dept. of Biology, St. Paul, MN, 1984.<br>
        University of Wisconsin, Dept. of Entomology, Madison, WI, 1984.<br>
        University of Wisconsin, Dept. of Genetics, Madison, WI, 1984.<br>
        University of Florida, Dept. of Zoology, Gainesville, FL, 1982.<br>
        University of Wisconsin, Dept. of Genetics, Madison, WI, 1982.</div>
        <br>

        <h4><u>ORAL PRESENTATIONS ("contributed papers")</u></h4>
        <div>European Society for Evolutionary Biology, Montpellier, France, 1993.<br>
        Society for the Study of Evolution, 1980, 1981, 1982, 1984, 1985, 1986, 1989, 1991, 1993.<br>
        Animal Behavior Society, 1989, 1991, 1993.<br>
        Conference on Extrachromosomal Elements in Lower Eukaryotes, U. Illinois, Urbana, IL, 1986.<br>
        Genetics Society of America, 1980, 1985.<br>
        Guild of Rocky Mountain Population Biologists, Boulder CO, 1982.</div>
        <br>

        <h4><u>TEACHING GRANTS AND FELLOWSHIPS</u></h4>
        <div>Indiana University Campuswide Writing Program, Writing-in-the-Classroom Fellowship, 1992.<br>
        Indiana University Multi-disciplinary Ventures Program, 1990-91, <i>Seminar on the Evolution of Learning.</i> (with W. Timberlake).<br>
        Indiana University Summer Faculty Fellowship, 1988.</div>
    </div>
  </div>
</div>